### PR TITLE
Implement Missing Serializations, Refactor Unit tests, Define Default and Unspecified CRS

### PR DESCRIPTION
**Pull request by russcam**
Hopefully the commit messages explain the changes but to summarize:

1. Refactored existing unit tests into separate classes and files, each responsible for testing only one system/thing
2. Swapped out MSTest for NUnit to allow ease of writing parameterized tests
3. Added missing test cases for certain geo json types
4. Implemented Equality members on all geometry objects
5. Optimized serialization/deserialization in Converters
6. Implemented missing serialization/deserialization implementations for geojson types e.g. MultiPoint, GeometryCollection
7. Introduced the concept of a Default CRS and Unspecified CRS as per the geojson spec i.e. if a null value is specified for a geojson crs property, this means that the CRS cannot be assumed. However, if no crs property is given then the Default CRS should be used (a geographic coordinate reference system, using the WGS84 datum, and with longitude and latitude units of decimal degrees). The current implementation treats both a null CRS and the lack of a CRS in the geojson object as the same thing, which is incorrect. Since the library is compiled to work with Portable Class libraries, a TypeConverter cannot be used to handle initializing the CRS property on a GeoJSONObject type to a default CRS, so the serialization/deserialization handling is performed via private serialization/deserialization methods.

### CODE REVIEW

**Comment by russcam** [comment]
I should also point out that there's a good chance that I might have broken backwards compatibility, in case this affects your versioning system

**Comment by jbattermann** [comment]
@russcam oh my, nice - I'll have a closer look later today (about to head out) and regarding breaking changes: those are 'ok'.. if there are any I'll go ahead and make a major version jump.

**Comment by russcam** [comment]
@jbattermann cool, if there's any questions about the changes, just let me know. There's a few more things that I am considering doing to handle

1. different `Position` implementations
2. the case where a `*Converter` instance is passed to `JsonSerializer` or `JsonConvert` and an attempt is made to serialize a geojson object that is associated with that converter implementation. You will get an exception relating to a circular dependency because in reality, the `*Converter` types are used to handle the `Coordinates` property of geojson types and not the entire object itself (except the `PointConverter`, which converts `GeographicPosition` types). 

An example

```c#
[Test]
public void Can_Serialize()
{
	var polygon = new Polygon(new List<LineString>
	{
		new LineString(new List<GeographicPosition>
		{
			new GeographicPosition(52.379790828551016, 5.3173828125),
			new GeographicPosition(52.36721467920585, 5.456085205078125),
			new GeographicPosition(52.303440474272755, 5.386047363281249, 4.23),
			new GeographicPosition(52.379790828551016, 5.3173828125),
		})
	});

	var expectedJson = GetExpectedJson();
	var actualJson = JsonConvert.SerializeObject(polygon, new PolygonConverter());

	JsonAssert.AreEqual(expectedJson, actualJson);
}
```

will result in

> Newtonsoft.Json.JsonSerializationException : Self referencing loop detected with type 'GeoJSON.Net.Geometry.Polygon'. Path ''.

**Comment by jbattermann** [comment]
Yikes - that was one big PR - thanks a lot @russcam .. really - great work!! I've merged it in as is and bumped the version to 0.*1*.x and since the library itself is still < v1 any potential breaks are fine with me.

Cheers,
-J

**Pull request merged**
